# Generated by Django 3.1.7 on 2021-02-26 13:58

from django.db import migrations, models
import lorem
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default=products.models.generate_code, max_length=4, unique=True)),
                ('desc', models.CharField(default=lorem.sentence, max_length=1024)),
            ],
        ),
    ]
