# Generated by Django 3.1.7 on 2021-02-26 16:40

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=products.models.generate_price),
        ),
    ]
