# Generated by Django 3.1.7 on 2021-02-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210224_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='AAAAAAAA', max_length=64),
        ),
    ]
