# Generated by Django 3.1.7 on 2021-02-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
