# Generated by Django 3.1.7 on 2021-02-26 13:58

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20210226_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=customers.models.generate_code, max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
