# Generated by Django 3.1.7 on 2021-02-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_order_customer'),
        ('products', '0004_auto_20210226_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
